### ISSUE TITLE
ラベル の設定（カスタムラベルの名称と色）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/ChQiita-Dev#1]
## 報告

`ChQiita-Dev` リポジトリのラベルカラーを [Qithub のラベルカラー](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md#-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%A9%E3%83%99%E3%83%AB%E3%81%AE%E5%90%8D%E7%A7%B0%E3%81%A8%E8%89%B2-items-5)に準拠しました。確認 & close 🙇 💪 

- [`ChQiita-Dev` REPO のラベル設定画面](https://github.com/Qithub-BOT/ChQiita-Dev/labels)
- [`Qithub` の全体仕様・とりまとめ](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md)
    - [`Qithub` の「ラベル」に関するルール・方針](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md#-%E3%83%A9%E3%83%99%E3%83%AB)

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連issue： Qithub-BOT/items/issues/5

**Comment by hidao80** [comment]
👍
