### ISSUE TITLE
ChQiita ブランチの取り扱い（マージ先）について

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/ChQiita-Dev#3]
## 質問

> ChQiita アプリへの PR は、どこにすればいいの？

## TL;DR（結論 2018/01/04）

- PR は `Qithub-BOT/ChQiita-Dev` リポジトリにお願いします
- ブランチは [Qithub の運用ルール](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md#%E9%81%8B%E5%96%B6%E3%83%AB%E3%83%BC%E3%83%AB)に準拠します

![qithub-chqiita-repo](https://user-images.githubusercontent.com/11840938/34554959-b54a445a-f172-11e7-9883-5a2c007dd28f.png)

### 決定事項（ [閉鎖済み旧 issue](https://github.com/Qithub-BOT/ChQiita/issues/3) より引き継ぎ）

- [本家](https://github.com/increments/kobito-oss)には PR しない（本家とは機能の趣旨が違うため）
- リリース用と開発用でリポジトリを分ける
    - リリース用リポジトリ： [`Qithub-BOT/ChQiita`](https://github.com/Qithub-BOT/ChQiita)
    - 開発用リポジトリ： [`Qithub-BOT/ChQiita-Dev`](https://github.com/Qithub-BOT/ChQiita-Dev)
- 各自の改造・改善 PR は `Qithub-BOT/ChQiita-Dev` で行う
- リリースは[プログラムチーム](https://github.com/orgs/Qithub-BOT/teams)が `ChQiita-Dev`→`ChQiita`にマージを行う
- `ChQiita` アプリの issue は `ChQiita-Dev` リポジトリ側で行う
- PR・マージ・ブランチの切り方など、[リポジトリの管理は Qithub 全体仕様に準拠](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md#%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E7%AE%A1%E7%90%86)

#### 関連

-  [Qithub 設定資料集（全体仕様・とりまとめ）](https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md)
- 関連 issue: Qithub-BOT/ChQiita/issues/3 （元のissue. 2018/01/04 閉鎖）

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
`Qithub-BOT/ChQiita` の issue から引っ越しました。問題なければ Close お願いし 💪 
その後 `ChQiita` repo の issue 機能は閉鎖します。

**Comment by hidao80** [comment]
👍

…むぅ！ リポジトリのメンバーになって無いらしくて、私からは Close できません！

メンバー追加対応と close お願いします！🙇🙏

**Comment by KEINOS** [comment]
> リポジトリのメンバーになって無いらしくて、私からは Close できません！

Organization のチームをリポジトリに追加する必要がありました。失念しておりました！

<kbd><img width="819" alt="2018-01-04 19 05 03" src="https://user-images.githubusercontent.com/11840938/34558680-64420b82-f182-11e7-8d14-500c251899f7.png"></kbd>

いかがでしょう？

**Comment by hidao80** [comment]
👌👍😄
